config:
  save-path: 'm2s'
  load-path: null
  result-path: 'results'
  dataset-path: 'data/AradVal'
  init-epoch: 0
  max-epoch: 200
  batch-size: 1
  workers: 0
  network:
    input_shape: [256,256,31]
    model: 'unet'
    lr: 0.0001 
    use_inr: True 
    param: 0.2
    optical_info:
      stride: 1
      patch_size: 128
      mask_path: null
      trainable_mask: True
      mask_seed: null
      is_patch: True 
      use_inr: True
      inr_info:
        model: 'relu'
        in_features: 2
        hidden_features: 128
        layers: 3
        out_features: 1
        # w0: 10
        # w1: 10
        # s0: 40 
        binarize: True
        use_pe: True
        outermost_linear: True
        pe_info:
          N_freq_by_dim: [8, 5]
          deterministic: True
          exp_freq_map: False
          std: 1.0